domain_path: C:\Users\danie\Documents\GitHub\GateKeeper\FPGA\vitis\GateKeeperVitis\export\GateKeeperVitis\sw\GateKeeperFSBL
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
